---

- name: Create ssh private/public and store in vault secret
  hosts: localhost
  connection: local
  gather_facts: no
  become: no

  roles:
    - role: azure-secret-ssh-keys
      become: false
      delegate_to: localhost
      vars:
        azure_secretsshkey_state: present
        azure_secretsshkey_force: no
